version: "3.8"
networks:
  mired2:
    ipam:
      config:
        - subnet: 182.28.0.0/16
          gateway: 182.28.0.1
services:
  mysqldb:
    image: mysql:5.7
    container_name: Mysql5
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
      - --skip-character-set-client-handshake
      #- --lower_case_table_names=0
    restart: always
    environment:
      MYSQL_DATABASE: "tiendadinfinito"
      MYSQL_USER: "tdi"
      MYSQL_PASSWORD: "tdi"
      MYSQL_ROOT_PASSWORD: "root"

    ports:
      - 3311:3306
    expose:
      - 3306
    volumes:
      - ./res/db/mysql/db:/var/lib/mysql
  backendtdi:
    image: bluishres/latiendadelinfinitoback:5
    container_name: Backend
    expose:
      - 8080
    ports:
      - 8080:8080

